### PR TITLE
Open quick pallet for folders that starting on the same

### PR DESCRIPTION
**Pull request by stoivo**
if you whould have 3 folders like
 - foobar
 - folder
 - folder_with_longer_name

When you type `fo` and tab it will open quick pallet as before
When you type `folder` and tab it will open quick pallet with
folder andfolder_with_longer_name. This commit is fixing that.

### CODE REVIEW

**Comment by rosshemsley** [comment]
Interesting, is this what completion in e.g. bash does?

**Comment by stoivo** [comment]
Yes, this is the behavior bash has. 

The problem was actual that it added `sep` if the folder exist, something that is true.

**Comment by stoivo** [comment]
ping

**Comment by stoivo** [comment]
pong

**Comment by stoivo** [comment]
pang

**Comment by stoivo** [comment]
💥

**Comment by rosshemsley** [comment]
@stoivo Hello! Sorry, after getting spammed with notifications by github, I had them set to off... but I finally found this!

I do not have much time to work on this project unfortunately,
However I have added you as a collaborator to the repo, which should give you full permissions to make changes :) 

Nnote: You may need to tag in a new release (appropriately following semver) to be able to see it in ST.

**Comment by stoivo** [comment]
Thank you for the opertunety to update the package. I will try to clear up some backlog and make a new release.

**Pull request merged**
